
CREATE DATABASE IF NOT EXISTS $POSTGRES_DB ;

DO
$$
BEGIN
	IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = $POSTGRES_USER) THEN
		CREATE ROLE $POSTGRES_USER LOGIN PASSWORD $POSTGRES_PASSWORD ;

GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB.* TO $POSTGRES_USER ;